# nenly phabricator service
FROM centos:7.6.1810

RUN useradd phabricator

RUN yum update -y \
    && yum install -y https://mirror.webtatic.com/yum/el7/webtatic-release.rpm \
    && yum install -y git php71w-devel php71w php71w-cli php71w-common php71w-gd php71w-ldap \
    php71w-mbstring php71w-mysqlnd php71w-fpm php71w-process php71w-opcache nodejs which \
    && yum clean all && chmod 777 /var/log

RUN mkdir /data && git clone https://github.com/phacility/libphutil.git "/data/libphutil" && \
    git clone https://github.com/phacility/arcanist.git "/data/arcanist"
RUN git clone https://github.com/phacility/phabricator.git "/data/phabricator"

WORKDIR /data/phabricator/support/aphlict/server
RUN npm --registry=https://registry.npm.taobao.org --cache=$HOME/.npm/.cache/cnpm --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc install ws && \
    chown -R phabricator.phabricator /data && \
    sed -i 's#/var/tmp/aphlict/pid/aphlict.pid#/tmp/aphlict.pid#' /data/phabricator/conf/aphlict/aphlict.default.json && \
    sed -i 's/127.0.0.1/0.0.0.0/' /data/phabricator/conf/aphlict/aphlict.default.json

WORKDIR /data/phabricator

EXPOSE 22280 22281

USER phabricator

CMD [ "/data/phabricator/bin/aphlict", "debug" ]
